### PR TITLE
utile.inspect is fixed in node >=0.6.4

### PR DESCRIPTION
**Pull request by timoxley**
inspect was fixed

https://github.com/joyent/node/issues/2225

### CODE REVIEW

**Comment by pksunkara** [comment]
Still a lot of people use `node 0.4`

@indexzero should decide on this.

**Comment by timoxley** [comment]
Agreed, I figured that would be the case.

**Comment by mrienstra** [comment]
How about using `process.version` to detect node version >= 0.6.4?

http://nodejs.org/docs/latest/api/process.html#process.version

Then utile can continue to support node 0.4, and people with newer versions of node will be able to access `util.inspect` via `utile.inspect`.

**Comment by timoxley** [comment]
That's a good idea IMO.

**Comment by mmalecki** [comment]
At this point no one should be using node v0.4. Merged in d2634a4a9aa2a4b620140f472338db1dbbe41c69, thanks Tim.

**Comment by timoxley** [comment]
:+1:

**Pull request closed without merging**
